services:
  - type: web
    name: trsh-dashboard
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: X-Robots-Tag
        value: noindex
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 18.20.0
      - key: REACT_APP_ANTHROPIC_API_KEY
        sync: false