services:
  # Frontend - React Static Site
  - type: web
    name: trsh-dashboard
    runtime: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./build
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: X-Robots-Tag
        value: noindex
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: REACT_APP_ANTHROPIC_API_KEY
        sync: false
      - key: REACT_APP_API_URL
        value: https://trsh-backend.onrender.com

  # Backend - Express API Server
  - type: web
    name: trsh-backend
    runtime: node
    rootDir: ./backend
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: DATABASE_URL
        sync: false
      - key: NODE_TLS_REJECT_UNAUTHORIZED
        value: "0"
      - key: FRONTEND_URL
        value: https://trsh-x3tb.onrender.com